name: Pandoc PDF

on:
  # triggered manually
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pandoc_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our semester-repo
        uses: actions/checkout@v7
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
      - name: Run Pandoc
        run: |
          mkdir targets
          find lecture homework -name '*.md' -exec sh -c 'mkdir -p targets/${1%/*} && pandoc --pdf-engine=xelatex -o targets/"${1%.*}".pdf ${1}' - '{}' \;      - name: Publish targets
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: _pdfs
          publish_dir: targets
          destination_dir: targets
          force_orphan: true
