name: Pandoc PDF

on:
  # triggered manually
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  pandoc_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our semester-repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install pandoc
        # uses: docker://pandoc/extra:latest-debian
        run: |
          sudo apt install pandoc texlive-xetex texlive-full -y
      - name: Run script
        run: |
          mkdir targets
          find lecture -name '*.md' -exec pandoc --pdf-engine=xelatex "{}" -o "targets/{}.pdf" \;
      - name: Publish targets
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: _pdfs
          publish_dir: targets/
          force_orphan: true
